apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# base/kustomization.yaml
resources:
  - deployment.yaml

images:
  - name: nginx
    newTag: "1.19.6"
    newName: "nginx"  # This is optional if the name remains unchanged
