resources:
  - ../../base  # Reference to the base Kustomize directory

patchesJson6902:
  # Patch for the Deployment object in prod environment
  - target:
      version: apps/v1
      kind: Deployment
      name: nginx
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: nginx:stable

  # Patch for the Service object in prod environment
  - target:
      version: v1
      kind: Service
      name: nginx
    patch: |
      - op: replace
        path: /spec/ports/0/port
        value: 80

