apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# overlays/production/kustomization.yaml
bases:
  - ../../base

patchesStrategicMerge:
  - nginx-deployment-patch.yaml

# images:
#   - name: nginx
#     newTag: "1.21.0"  # Specify a new version of NGINX for the production environment
