apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

helmCharts:
  - name: opensearch
    version: "2.30.0"
    repo: https://opensearch-project.github.io/helm-charts
    releaseName: opensearch-production
    namespace: logging
    valuesFile: ./values-production.yaml