apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml

helmCharts:
  - name: opensearch
    version: 2.6.0
    repo: https://opensearch-project.github.io/helm-charts
    releaseName: opensearch
    namespace: logging
    valuesFile: values.yaml
