apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: myapp-config
    literals:
      - MYAPP_ENV=dev
      - MYAPP_DEBUG=false


secretGenerator:
  - name: myapp-secret
    literals:
      - DB_PASSWORD=secret_password
    type: Opaque

patchesStrategicMerge:
  - patch-deployment.yaml

