apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
secretGenerator:
  - name: app-secret  # The name of the secret we want to generate
    literals:
      - DATABASE_URL=dev-database-url
      - API_KEY=dev-api-key
    type: Opaque
