apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - https://charts.bitnami.com/bitnami/grafana-6.19.1.tgz  # Grafana Helm chart reference

helmCharts:
  - name: grafana
    version: "8.8.2"
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    valuesFile: ./values.yaml  # Common base values for the Helm chart
