clusterName: opensearch-cluster
nodeGroup: data
replicas: 3
service:
  type: ClusterIP
  port: 9200

persistence:
  enabled: true
  size: 10Gi
  storageClass: "standard"

plugins:
  - opensearch-security
  - opensearch-performance-analyzer

resources:
  limits:
    memory: 2Gi
    cpu: "1"
  requests:
    memory: 1Gi
    cpu: "500m"
