apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring
resources:
  - namespace.yaml

helmCharts:
  - name: grafana
    releaseName: grafana
    version: 8.8.2  # Specify the chart version
    repo: https://grafana.github.io/helm-charts
    namespace: monitoring
    valuesFile: grafana-values.yaml